spring.application.name=setas-backend

#Nos conectamos a la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/setas_db
spring.datasource.username=postgres
spring.datasource.password=$admin123

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Puerto del server
server.port=8080