spring.application.name=setas-backend

#Nos conectamos a la base de datos
spring.datasource.url=jdbc:postgresql://db.yxopvusbskyataupxzdc.supabase.co
spring.datasource.username=postgres
spring.datasource.password=$.9422k3232K.$

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Puerto del server
server.port=8080

#JWT
jwt.secret=xuKA7ThCUmphJdxLJh8nI85xxnszDPIr2mKFy6PjfAk=
jwt.expiration=86400000